// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import KeyboardGameController from "./keyboard_game_controller"
application.register("keyboard-game", KeyboardGameController)

import MouseGameController from "./mouse_game_controller"
application.register("mouse-game", MouseGameController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
