services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: "sqlite3:/app/db/development.sqlite3"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_data:
  node_modules: