services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: "sqlite3:/app/db/development.sqlite3"
    ports:
      - "3000:3000"

volumes:
  bundle_data:
  node_modules: